name: Swift

on:
  push:
    branches:
    - master
    - release/*
    - develop

  pull_request:
    branches:
    - master
    - develop
      
jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild build -scheme Drawer -project Drawer.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.2.2' | xcpretty && exit ${PIPESTATUS[0]}

