name: Swift

on:
  push:
    branches:
    - master
    - release/*
    - develop

  pull_request:
    branches:
    - master
    - develop
      
jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: List available Xcode versions
      run: ls /Applications | grep Xcode
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.1.app && /usr/bin/xcodebuild -version
    - name: Build
      run: xcodebuild build -scheme Drawer -project Drawer.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' | xcpretty && exit ${PIPESTATUS[0]}

